### ISSUE TITLE
Syntax highlighting in YAML fails with quotes

### ISSUE THREAD

**Issue by alexmbird** [atg/chocolat-public#1767]
```
---
- name: "Install docker-engine, version {{ docker_engine_version }}"
  apt: pkg="docker-engine={{ docker_engine_version }}" state=installed update_cache=true cache_valid_time=3600
  sudo: yes
  tags:
    - docker_setup
    - initial_setup
  notify: Restart docker-engine

- name: Generate /etc/default/docker
  notify: Restart docker-engine
```

Highlighting fails somewhere on the `apt: pkg="docker-engine` line and the rest of my file is treated as quoted text.  Please to fix, I keep messing up my YAML :(
